POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email":"TestFrontEndAluno@email.com",
    "password":"AlunoSenha@1"
}

POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email":"JuJuMira@email.com",
    "password":"Professor@1"
}