POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email":"TestBackend2@email.com",
    "password":"AlunoSenha@1"
}

POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email":"GabMira@email.com",
    "password":"Professor@1"
}