POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email":"TestFrontend@email.com",
    "password":"AlunoSenha@1"
}

POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email":"GustavoProfessor@email.com",
    "password":"Professor@1"
}