GET http://localhost:3000/disciplines/by/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInJvbGUiOiJURUFDSEVSIiwiZW1haWwiOiJKdUp1TWlyYUBlbWFpbC5jb20iLCJpYXQiOjE3NjEwMDM1MTgsImV4cCI6MTc2MTA4OTkxOCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.sehj25KfmrDkkFnZb_y50xddmDF1hgLjbrBQ8_v_9uk