GET http://localhost:3000/disciplines/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInJvbGUiOiJURUFDSEVSIiwiZW1haWwiOiJHYWJNaXJhQGVtYWlsLmNvbSIsImlhdCI6MTc2MDk5NzgwOSwiZXhwIjoxNzYxMDg0MjA5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.g2BFqHlrRJS9lPSWszA7Z_3Xx2qhhJ_OgalBo8kxBy4