GET http://localhost:3000/disciplines/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiVGVzdEJhY2tlbmRAZW1haWwuY29tIiwiaWF0IjoxNzYwMTIwMTQ3LCJleHAiOjE3NjAyMDY1NDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.xHDStkJMD8AISvG3gyEGzOVT0dajvR3gEwe4RoqU2QY