GET http://localhost:3000/disciplines/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiVGVzdEZyb250RW5kQWx1bm9AZW1haWwuY29tIiwiaWF0IjoxNzYxMDg5NzAyLCJleHAiOjE3NjExNzYxMDIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.jQ-HZDEgHOK2qbDzbtzHd5jnGp7Gox_0vjAHhlKwxK8
