POST http://localhost:3000/disciplines/start-face-recognition
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsInJvbGUiOiJURUFDSEVSIiwiZW1haWwiOiJWaXRvck1pcmFAZW1haWwuY29tIiwiaWF0IjoxNzU5NzYxOTY4LCJleHAiOjE3NTk4NDgzNjgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.50TBZcmdHo6dA7odpptKM3-oUKnBGPoplsN2egcKx9I

{
    "id": 8
}