POST http://localhost:3000/disciplines/stop-face-recognition
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiVGVzdEJhY2tlbmRAZW1haWwuY29tIiwiaWF0IjoxNzYwMTA0MTE0LCJleHAiOjE3NjAxOTA1MTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.2ICxrSVrTnoWtNZ38VX7r9hR8l2yYnbIt97AJMr-CTA

{
    "id": 8
}