POST http://localhost:3000/disciplines/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiVGVzdEJhY2tlbmRAZW1haWwuY29tIiwiaWF0IjoxNzYwNzQ2NDA5LCJleHAiOjE3NjA4MzI4MDksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ._zwocI4_wmfGITzzZiWexAXDEH2TSAfBkCCZIh7iNy8

{
    "name" :"Aula 1",
    "code": "SDES09",
    "semester": "2025.1",
    "disciplineTime": ["5T34","2N12"],
    "disciplineRoom": "C1113",
    "ipCamera": 0
}