POST http://localhost:3000/disciplines/
Content-Type: application/json

{
    "name" :"Gerência de Projetos de Software",
    "code": "SDES06",
    "semester": "2025.1",
    "disciplineTime": ["5N34","6N12"],
    "disciplineRoom": "C1113",
    "ipCamera": "1.1.1.100",
    "teacher": 4,
    "students": [7]
}